### ISSUE TITLE
generation of `messageSize()` uses deprecated `sumBy()` function

### ISSUE THREAD

**Issue by RaphaelTarita** [open-toast/protokt#117]
Apparently, the generation of message types, or more precisely, the generation of 
```kotlin
private fun messageSize(): Int {
    // ...
}
```
uses the extension function
```kotlin
public inline fun <T> Iterable<T>.sumBy(selector: (T) -> Int): Int {
    // ...
}
```
which is marked as deprecated since Kotlin 1.5. A drop-in replacement for this function is provided (`@ReplaceWith`) and it's called `sumOf()` (which exists since Kotlin 1.4). I had a look at the source code and it seems that these two functions really are the same. The only three differences I could spot were
1. The name (obviously)
2. A superfluous `.toInt()` in the _newer_ (!) `sumOf()`
3. The newer `sumOf()` uses the experimental overload resolution by lambda return type (`@OverloadResolutionByLambdaReturnType`), which means that now there aren't `sumOfDouble()`, `sumOfLong()` and so on, but multiple overloads that only differ in the return type of the passed lambda.

Considering all of this, migrating from `sumBy()` to `sumOf()` should be as trivial as just replacing the name at each usage.
I think it would be a good idea to do this migration soon, since Kotlin might remove the old `sumBy()` soon (or change its semantics), and also all the warnings that are generated are a bit annoying.

Version Data:

- Kotlin/JVM 1.5.21
- OpenJDK 16 (target / language level 11)
- ProtoKt 0.6.2
- ProtoBuf 3.15.3
- gRPC 1.1.0

**Comment by andrewparmet** [comment]
Released in 0.6.3. Thanks for the report!
