### ISSUE TITLE
Write out the DescriptorSet

### ISSUE THREAD

**Issue by codefish1** [open-toast/protokt#120]
On our maven/Java based projects we are using org.xolstice.maven.plugins:protobuf-maven-plugin to generate our protobuf objects and to also output the DescriptorSet.

We are using it in a similar way to https://github.com/os72/protobuf-dynamic to enable us to dynamically turn the byte[] into JSON for storage on our dead letter queue (DLQ) without the DLQ needing to know about all the various schemas at compile time.

I can't see an option to produce this.  Is it just missing in the documentation or does it still need to be implemented?

**Comment by andrewparmet** [comment]
This work is actually in progress: https://github.com/open-toast/protokt/pull/105. We don't have immediate plans to support the JSON spec, but if you're just after human readability then GSON or Jackson should be enough to work with once you have the object deserialized.

Feel free to take that branch for a test drive and let me know if it has everything you need.

**Comment by andrewparmet** [comment]
#105 has been merged and release in 0.6.5.
