### ISSUE TITLE
Duplicated names in included protos cause problems

### ISSUE THREAD

**Issue by pranjalvachaspati-toast** [open-toast/protokt#159]
I'm still trying to find a simple test case for this, but the issue is roughly

- Project 1 has foo/something.proto and bar/something.proto, which contain protos `foo.Something` and `bar.Something` respectively
- Project 2 has a proto that includes one or both `Something`s. 
- The disambiguation code while compiling Project 1 called the `foo.Something` descriptor object `SomethingProto_` and the `bar.Something` proto `SomethingProto__`
- But Project 2 doesn't know this, so it's looking for `SomethingProto`.

Not 100% sure what the solution should be, maybe using fully qualified names where necessary.

**Comment by andrewparmet** [comment]
The descriptor objects should be qualified with Java/Kotlin/Proto (precendentially) package names, right?

**Comment by pranjalvachaspati-toast** [comment]
Yeah, the problem is the code here https://github.com/open-toast/protokt/blob/8e4674b8a22dab7d455c40ccbe2efc916258c373/protokt-codegen/src/main/kotlin/com/toasttab/protokt/codegen/protoc/Format.kt#L190

It means that the code generated for a proto depends on the other protos that have been compiled in the same protoc invocation.

So if we didn't do that, and instead disambiguated only on a per-package basis, we would need to make sure we're using fully-qualified names elsewhere in the generated code in some cases. I think KotlinPoet should do at least some of this, I'm working on a PR to make this work.

**Comment by andrewparmet** [comment]
Ah I follow - I missed the second underscore. We do need a deterministic way to generate file descriptor names.
