### ISSUE TITLE
New protobuf-java versions cause generated code to fail to compile

### ISSUE THREAD

**Issue by andrewparmet** [open-toast/protokt#191]
```
build/generated-sources/main/protokt/com/toasttab/protokt/descriptor.kt:1290:13 Platform declaration clash: The following declarations have the same JVM signature (setRepeated(Ljava/lang/Boolean;)V):
    fun `<set-isRepeated>`(`<set-?>`: Boolean?): Unit defined in com.toasttab.protokt.ExtensionRangeOptions.Declaration.DeclarationDsl
    fun `<set-repeated>`(`<set-?>`: Boolean?): Unit defined in com.toasttab.protokt.ExtensionRangeOptions.Declaration.DeclarationDsl
```

**Comment by connormcauliffe-toast** [comment]
They added a new field to replace `is_repeated` in the `Declaration` proto inside the `ExtensionRangeOptions` and named it `repeated`, which in Kotlin both generate the same setter for Java. They removed the field in 3.24.0+ https://github.com/protocolbuffers/protobuf/commit/96c601d8b470307a99c1ac1fbf56a66dbfd0aac2
Trying the version bump locally to see if it fixes it
