### ISSUE TITLE
Proxy needed for browser?

### ISSUE THREAD

**Issue by pusolito** [open-toast/protokt#199]
I've seen that gRPC requires a proxy server on the backend when used from browsers, which do not provide the low-level access to HTTP2 that gRPC needs. But I don't  see that mentioned in the docs, like it is in the [grpc-web](https://github.com/grpc/grpc-web) docs. Can you confirm whether a proxy is still needed?

**Comment by andrewparmet** [comment]
Yes, a proxy is still needed. Protokt's JS runtime implementation is a wrapper around `grpc-js` so it inherits both good and annoying baggage.

**Comment by pusolito** [comment]
I assume this means bundle size is also a bit bigger since gRPC-web creates its own code and protokt has to provide wrappers around those JS message types the client to make the APIs more idiomatic Kotlin. Is that right?

Also, why is the your browser support considered alpha still given gRPC-web is fairly far along?

**Comment by andrewparmet** [comment]
I'm not sure about the bundle size; I've never used `grpc-web`.

Protokt's JS implementations are brand new.

Protokt's support for serialization and deserialization in JS is not alpha - it passes all the same conformance tests as the JVM implementation.

The gRPC runtime for JS is alpha - there are tests covering happy paths for each type of call, but it's likely that error propagation doesn't work properly in all cases. For example, it's possible that a StatusException (defined in this project to be analogous to `grpc-java`'s StatusException) with a particular gRPC status may not be received by the client as the same status.

**Comment by pusolito** [comment]
This is really helpful. I'll give the library a shot.

I appreciate the work something like this takes. So thank you and keep it up.

**Comment by andrewparmet** [comment]
Feel welcome to open an issue for any bugs or feature requests. I don't know the JS ecosystem well enough to know what may be missing, especially for browser support of gRPC clients.

**Comment by andrewparmet** [comment]
Closing with grpc-web support covered by #202.
